version: '3.8'

networks:

  nestjs-postgres-network:
    driver: bridge

services:

  postgres-db:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    networks: 
      - nestjs-postgres-network
 
  nestjs-app-dev:
    build: 
      context: .
      target: development
    restart: always
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres-db
    volumes:
      - ./src:/app/src
    ports: 
      - "${PORT}:${PORT}"
    networks: 
      - nestjs-postgres-network
    depends_on: 
      - postgres-db
